### PR TITLE
Remove Alchemy service for Natural language understanding service

### PR DESCRIPTION
**Pull request by stevenpkg**

### CODE REVIEW

**Comment by stevenpkg** [comment]
@germanattanasio can you review this please

**Comment by stevenpkg** [comment]
@germanattanasio  Travis still fails, seems to be because it needs .env for credentials, only just started working on this app, what do you think?

**Comment by stevenpkg** [comment]
@germanattanasio Please review

**Comment by germanattanasio** [comment]
@stevenpkg sorry that I got that late to this PR. Seems like someone already made the update!

**Pull request closed without merging**
