### PR TITLE
update weather environment variables

### PR DESCRIPTION
**Pull request by stevemar**
- use the correct URL for the weather API
  https://api.weather.com

- use WEATHER_API_KEY instead of WEATHER_USERNAME
  and WEATHER_PASSWORD, since we're using an API
  key in our examples.

### CODE REVIEW

**Comment by MHBauer** [comment]
lgtm from the class earlier today.

**Comment by stevemar** [comment]
hmm, not sure why travis CI is complaining... "openssl aes-256-cbc -K $encrypted_f9d49e660b56_key -iv $encrypted_f9d49e660b56_iv -in .env.enc -out .env -d"  any ideas?

**Comment by germanattanasio** [comment]
@stevemart I like the changes but you need to also make sure that the code uses the new variables

**Comment by germanattanasio** [comment]
close due to inactivity

**Pull request closed without merging**
